version: '3.8'

services:
  store_module:
    env_file:
      - "../.env"
    build:
      context: .
    container_name: store_module
    restart: always
    ports:
      - "9083:8080"
    environment:
      MODULE_GROUP_ID: STORE_GROUP_ID
      SERVICE_PORT: 9080
#    deploy:
#      mode: replicated
#      replicas: 2

